# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Image Alignment
email: yumidwest@gmail.com
full_name: Yu Nakanishi
github_repository_url: https://github.com/yunakanishi/image-alignment
github_username_or_organization: yunakanishi
include_reader_plugin: true
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: false
install_precommit: false
license: MIT
module_name: image_alignment
plugin_name: image-alignment
short_description: alignment of imgaes with napariGUI
